name: Backup-zen Docker Image CI latest

on:
  push:
    branches: [ "main" ]
    paths: [ "docker" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "docker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push PostgreSQL-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/pg
          file: ./docker/pg/Dockerfile
          push: true
          tags: rezachalak/bzen-pg:latest
      -
        name: Build and push MongoDB-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/mongo
          file: ./docker/mongo/Dockerfile
          push: true
          tags: rezachalak/bzen-mongo:latest
      -
        name: Build and push MySQL-Backup-Zen
        uses: docker/build-push-action@v4
        with:
          context: ./docker/mysql
          file: ./docker/mysql/Dockerfile
          push: true
          tags: rezachalak/bzen-mysql:latest
